### ISSUE TITLE
System.PlatformNotSupportedException: Thread abort is not supported on this platform.

### ISSUE THREAD

**Issue by hohuuhau** [amibar/SmartThreadPool#25]
Hello,
I'm using NetCore version: 3.1.302, but when i running, have error:
`System.PlatformNotSupportedException: Thread abort is not supported on this platform.
   at System.Threading.Thread.Abort()
   at Amib.Threading.SmartThreadPool.Shutdown(Boolean forceAbort, Int32 millisecondsTimeout)
   at Amib.Threading.SmartThreadPool.Shutdown()`

I saw admin talk it support in versionn 3.1, but why when i use, it's can't work?

Any can help me?

**Comment by amibar** [comment]
Solved in version 2.3.0, added .net core support
